# Generated by Django 4.0.1 on 2022-06-17 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_small',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
                ('year', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
                ('github', models.URLField()),
                ('video_url', models.URLField()),
                ('tech', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField()),
                ('github', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('lusofona_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=0)),
                ('etcs', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('topics', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(blank=True, to='portfolio.Student')),
                ('subject_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project_small')),
                ('teacher_practice', models.ManyToManyField(related_name='practice_teacher', to='portfolio.Teacher')),
                ('teacher_theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('type', models.ManyToManyField(related_name='skills', to='portfolio.SkillType')),
            ],
        ),
        migrations.AddField(
            model_name='project_small',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student'),
        ),
        migrations.AddField(
            model_name='project_small',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='portfolio.Skills'),
        ),
        migrations.AddField(
            model_name='project_small',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='portfolio.Teacher'),
        ),
        migrations.CreateModel(
            name='Project_big',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
                ('year', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
                ('github', models.URLField()),
                ('video_url', models.URLField()),
                ('report', models.URLField()),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
                ('teacher', models.ManyToManyField(related_name='advisor', to='portfolio.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('post_image', models.ImageField(blank=True, upload_to='pictures/')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
